### ISSUE TITLE
Package still relevant ?

### ISSUE THREAD

**Issue by vogloblinsky** [blidblid/angular-cli-hooks#1]
Just tried to follow the README file.
`@berglund/angular-cli-hooks` seems deprecated but already referenced in README.
How can i simply hook `ng build`with this package ?
Thanks

**Comment by blidblid** [comment]
A new package is located at `angular-cli-hooks`, I ran the tests for Angular 18 and it should still work.

[angular-cli-hooks,](https://www.npmjs.com/package/angular-cli-hooks)
