### ISSUE TITLE
Clear tutorial for local hook

### ISSUE THREAD

**Issue by vogloblinsky** [blidblid/angular-cli-hooks#2]
I want to use your project inside an Angular project.

If i follow the README file, i just created a `builder-hooks` folder at the same level of `node_modules`, and put the `index.js` in it.

When i try install **angular-cli-hooks**, i have an error :

```
Error: Cannot find module 'builder-hooks'
```

Where am i wrong ?

I don't want to publish a package on npm just to extend Angular CLI just for one project.

Thanks

**Comment by blidblid** [comment]
The reason it's a hook package is because that's how Angular resolves builders. But you can always create a local package and reference it using your `package.json`:


```json
{
  "name": "demo-angular-cli-hooks",
  "devDependencies": {
    "builder-hooks": "file:./builder-hooks",
  }
}
```

I created a demo project here: https://github.com/blidblid/angular-cli-hooks-demo

**Comment by vogloblinsky** [comment]
Thanks i will try asap.
